{% set name = "pyiron_snippets" %}
{% set version = "1.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_snippets-{{ version }}.tar.gz
  sha256: 4f9d733282f6c96c97da1e74edd1c5899c447d18b5795a3781ae93a2418b14b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling ==1.28.0
    - hatch-vcs ==0.5.0
  run:
    - python >={{ python_min }},<3.15

test:
  imports:
    - pyiron_snippets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_snippets
  summary: pyiron_snippets - Short, dependency-free python snippets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - samwaseda
    - jan-janssen
    - niklassiemer
    - pyiron-runner
