{% set name = "pyiron_snippets" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_snippets-{{ version }}.tar.gz
  sha256: 5664f54e8326d4e2ba4ee03467754bccd58dcd81a17f358a297dff58f082c1f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - setuptools
    - versioneer ==0.29
    - pip
  run:
    - python >=3.9,<3.13

test:
  imports:
    - pyiron_snippets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_snippets
  summary: pyiron_snippets - Short, dependency-free python snippets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - samwaseda
    - jan-janssen
    - niklassiemer
    - pyiron-runner
