{% set name = "pyiron_snippets" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_snippets-{{ version }}.tar.gz
  sha256: c46532fe476c79d1182477709b7fa8a66c92e3ae6082c6ccfc0ebef1f69ed046

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - versioneer ==0.29
    - pip
  run:
    - python >={{ python_min }},<3.14

test:
  imports:
    - pyiron_snippets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_snippets
  summary: pyiron_snippets - Short, dependency-free python snippets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - samwaseda
    - jan-janssen
    - niklassiemer
    - pyiron-runner
